### ISSUE TITLE
Does not setup the bucket

### ISSUE THREAD

**Issue by wzr1337** [jayesh100/serverless-webapp-deployments-plugin#1]
I configured according to README.md, but the plugin will not create the bucket nor configure it. If I manually create the bucket, the plugin uploads the webapp correctly but still does not configure the bucket to be publicly accessible.

I assume config is right, because it uploads.

**Comment by nodejayesh** [comment]
Documentation was missing a field - just updated. Have a look at the `BucketName` property

**Comment by wzr1337** [comment]
fixed, thanks!
